### ISSUE TITLE
Suggestion: Disable all interactions on disabled form controls

### ISSUE THREAD

**Issue by juthilo** [db-ui/core#350]
Currently, when a disabled form control or button contains HTML elements (for example, icons or `span`s for internationalization), clicking on that part of the content is not actually disabled. That means, disabled submit buttons actually submit forms.

We used an override with `pointer-events: none` to circumvent this behavior. To my knowledge, this rule is common in other UI frameworks. Could it be added to Core?

Our override:
```scss
db-button, button, db-select, select, db-input, input {
	&[disabled] {
		pointer-events: none;
	}
}
```
